### PR TITLE
ci: print deployment logs right-aligned

### PR DESCRIPTION
**Pull request by gitcoindev**
Resolves: https://github.com/ubiquity/ubiquity-dollar/issues/728

### CODE REVIEW

**Comment by gitcoindev** [comment]
QA: https://github.com/korrrba/ubiquibot-logging/pull/1#issuecomment-1782886952

**Comment by gitcoindev** [comment]
Implementation note: I created alignRight helper function to avoid multiple issues I faced during editing / merging of the bot comments.

**Comment by gitcoindev** [comment]
Added option B styling with new QA: https://github.com/korrrba/ubiquibot-logging/pull/2

**Review by rndquu — APPROVED** [review]

**Review by molecula451 — APPROVED** [review]
looks good to me

**Pull request merged**
